from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
# ----Hint to K.B. ---- 
    path('change_profile/', change_profile, name='change-profile'),
    path('change_detail_profile/<int:pk>/', change_detail_profile, name='change-detail-profile'),
    path('profile_detail/<int:pk>/', profile_detail, name='profile-detail'),
    path('profile/', profile, name='profile'),
# ---------------------
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('forum/', forum, name='forum'),
    path('forum/create/', create_forum_post, name='create-forum-post'),
    path('forum/edit/<int:pk>/', edit_forum_post, name='edit-forum-post'),
    path('forum/delete/<int:pk>/', delete_forum_post, name='delete-forum-post'),
    path('register/', register, name='register'),
    path('create-advert/', add_advert, name='create-advert'),
    path('delete-advert/<int:pk>/', delete_advert, name='delete-advert'),
    path('update-advert/<int:pk>/', update_advert, name='update-advert'),
    path('adverts-list/', advert_list, name='adverts-list'),
    path('advert-detail/<int:pk>/', advert_detail, name='advert-detail'),
    path('add_grade/<int:pk>/', add_grade, name='add-grade'),
    path('grades_list/<int:pk>/', list_grades, name='list-grades'),
    path('edit_grade/<int:pk>/', edit_grade, name='edit-grade'),
    path('delete_grade/<int:pk>/', delete_grade, name='delete-grade'),
    path('polls/', polls_list, name='polls-list'),
    path('polls/<int:pk>/', poll_detail, name='poll-detail'),
    path('polls/<int:pk>/vote/', poll_vote, name='poll-vote'),
    path('polls/create/', create_poll, name='create-poll'),
    path('polls/<int:pk>/edit/', edit_poll, name='edit-poll'),
    path('polls/<int:pk>/delete/', delete_poll, name='delete-poll'),
    path('surveys/', surveys_list, name='surveys-list'),
    path('surveys/create/', create_survey, name='create-survey'),
    path('surveys/<int:pk>/edit/', edit_survey, name='edit-survey'),
    path('surveys/<int:pk>/delete/', delete_survey, name='delete-survey'),
    path('surveys/<int:pk>/take/', survey_take, name='survey-take'),
    path('surveys/<int:pk>/results/', survey_results_user, name='survey-results-user'),
    path('surveys/<int:pk>/results/admin/', survey_results_admin, name='survey-results-admin'),
    path('surveys/<int:pk>/add-page/', add_survey_page, name='add-survey-page'),
    path('surveys/page/<int:pk>/edit/', edit_survey_page, name='edit-survey-page'),
    path('surveys/page/<int:pk>/delete/', delete_survey_page, name='delete-survey-page'),
    path('surveys/question/<int:pk>/delete/', delete_survey_question, name='delete-survey-question'),
    path('create-forum-comment/<int:post_id>/', create_forum_comment, name='create-forum-comment'),
    path('delete-forum-comment/<int:forum_comment_id>/<int:post_id>/', delete_forum_comment, name='delete-forum-comment'),
    path('edit-forum-comment/<int:forum_comment_id>/<int:post_id>/', edit_forum_comment, name='edit-forum-comment'),
    path('forum-comments-list/<int:post_id>/', forum_comments_list, name='forum-comments-list'),
    path('forum-comment-detail/<int:forum_comment_id>/<int:post_id>/', forum_comment_detail, name='forum-comment-detail'),
    path('gallery-list/', gallery_media_list, name='gallery-list'),
    path('add-to-gallery/<int:profile_id>/', upload_to_gallery, name='add-to-gallery'),
    path('approve-addition/<int:media_id>/', approve_addition, name='approve-addition'),
    path('moderation-gallery/', moderation_gallery, name='moderation-gallery'),
    path('materials-list/', materials_list, name='materials-list'),
    path('material-detail/<int:material_id>/', material_detail, name='material-detail'),
    path('add-material/', add_material, name='add-material'),
    path('change-material/<int:material_id>/', change_material, name='change-material'),
    path('delete-material/<int:material_id>/', delete_material, name='delete-material'),
    path('accept-offer/', accept_offer, name='accept_offer'),
    path('', home, name='home'),
]