# Generated by Django 6.0.6 on 2026-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='advertisements_images/')),
                ('announcement_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
