# Generated by Django 6.0.4 on 2026-07-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profile',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_creator', to='main.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_files/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('file', 'Файл'), ('image', 'Картинка')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
    ]
