# Generated by Django 6.0.4 on 2026-07-24 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profile',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_creator', to='main.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio_files/')),
                ('url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('file', 'Файл'), ('image', 'Картинка'), ('url', 'Посилання')], default='image', max_length=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_media', to='main.portfolio')),
            ],
        ),
    ]
