# Generated by Django 6.0.4 on 2026-07-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_portfolio_options_remove_portfolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/events_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='events/events_files/')),
                ('url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('file', 'Файл'), ('image', 'Картинка'), ('url', 'Посилання')], default='image', max_length=20)),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.calendar')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='main.profile')),
            ],
        ),
    ]
