# Generated by Django 6.0.4 on 2026-08-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_grades', '__first__'),
        ('core_profile', '0001_initial'),
        ('main', '0002_calendar_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldiary',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_diaries', to='core_grades.grade'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='comment_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creator', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='digitaldiary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_diaries', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_creator', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='gallerymedia',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='gallerymedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core_profile.profile'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='core_profile.profile'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
