# Generated by Django 6.0.4 on 2026-07-13 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_forumpost_created_at_advertisement_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='announcement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
