# Generated by Django 6.0.4 on 2026-07-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_calendar_event'),
        ('main', '0003_calendar_event_eventmedia'),
    ]

    operations = [
    ]
