# Generated by Django 6.0.4 on 2026-07-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_grade_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='announcement_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=255)),
                ('comment_content', models.TextField()),
                ('comment_image', models.FileField(blank=True, null=True, upload_to='forum_comments_images/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('comment_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creator', to='main.profile')),
            ],
        ),
    ]
