# Generated by Django 6.0.4 on 2026-07-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_advertisement_announcement_date_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.forumpost'),
            preserve_default=False,
        ),
    ]
