# Generated by Django 6.0.4 on 2026-07-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.FileField(upload_to='gallery_images/')),
                ('status', models.CharField(choices=[('on_checking', 'On_checking'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='on_checking', max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='main.profile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='main.profile')),
            ],
        ),
    ]
