# Generated by Django 6.0.4 on 2026-07-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gallerymedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='gallerymedia',
            old_name='media_type',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='digitaldiary',
            name='grades',
        ),
        migrations.AddField(
            model_name='digitaldiary',
            name='grade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='digital_diaries', to='main.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.item'),
            preserve_default=False,
        ),
    ]
