# Generated by Django 6.0.7 on 2026-07-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_survey_surveypage_surveyquestion_and_more'),
        ('main', '0009_item_rename_media_type_gallerymedia_media_and_more'),
    ]

    operations = [
    ]
