# Generated by Django 6.0.4 on 2026-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20260716_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='item',
        ),
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
