# Generated by Django 6.0.4 on 2026-07-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_materials'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE main_materials
                RENAME COLUMN material_description TO description;
            """,
            reverse_sql="""
                ALTER TABLE main_materials
                RENAME COLUMN description TO material_description;
            """
        ),
    ]
