# Generated by Django 6.0.4 on 2026-07-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_grade_item_grade_description'),
        ('main', '0012_auto_20260719_1027'),
    ]

    operations = [
    ]
