# Generated by Django 6.0.4 on 2026-08-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryMedia',
        ),
    ]
