# Generated by Django 6.0.6 on 2026-08-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_grades', '0001_initial'),
        ('core_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core_profile.profile'),
        ),
    ]
